version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: graduateworkmachines.azurecr.io/machines-app
    container_name: "api"
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - project
  database:
    container_name: "database"
    image: mysql
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      - project

networks:
  project:
    driver: bridge